### ISSUE TITLE
Argument 1 passed to Google_Cache_File::__construct() must be an instance of Google_Client, string given

### ISSUE THREAD

**Issue by triasrahman** [rainlab/googleanalytics-plugin#40]
What's wrong?
![screen shot 2016-02-14 at 4 08 16 pm](https://cloud.githubusercontent.com/assets/7110859/13032838/37954300-d335-11e5-8b15-b9f666b4c6a7.png)

After I update to the v1.1, this error happens. I've uploaded the json key, trying to remove and install the plugin, but it still happens :/
It works on previous version.. Need your help, thanks!

**Comment by daftspunk** [comment]
Something doesn't look right there, the [first arg is supposed to be a string](https://github.com/google/google-api-php-client/blob/master/src/Google/Cache/File.php#L40). Try completely removing the googleanalytics directory before reinstalling.

Do you have any other plugins installed that use the Google PHP library?

**Comment by triasrahman** [comment]
Oh, you're right. I've tried to remove the [Flynsarmy.SocialLogin plugin](https://octobercms.com/plugin/flynsarmy-sociallogin). It's conflicted because it's also using Google library for G+ OAuth. How to resolve this?

**Comment by Eoler** [comment]
There are other plugins that use different version of Google PHP API:
http://octobercms.com/plugin/martin-ssologin

What is OctoberCMS way to keep plugin Composer dependencies independent from core?

**Comment by daftspunk** [comment]
The Google API client is still in beta and implemented some major breaking changes with the 2.0 release. This makes any plugin that uses the 1.0 library version incompatible until they update to 2.0 as well.

This creates a problem for plugins that use the same library because PHP, like most languages, is not capable of running 2 versions of the same library. This has been discussed and the following guidelines should be followed:

- If using a 3rd party library, always endeavor to use the latest version available

- When instances of conflict like these are found, the plugin authors should be notified.

- Any time this occurs, it requires work for the author to publish a fix. Unfortunately abandoned plugins must be abandoned in use or forked by someone else.

- The author can choose to upgrade the library to latest, or remain using the old version.

- To remain on an old version, the library should be forked and the namespace changed, eg: `Google\Client` renamed to `GoogleV1\Client` and included with the plugin manually, or published as a new composer package, which may require permission and maintenance overhead.

- If the "old" plugin remains compatible, then it should be tagged as a version in GitHub, so users can downgrade manually and stay with the old plugin.

In this case, the V1 Google PHP library [appears to be broken](https://github.com/google/google-api-php-client/issues/795) because it was released along side some API changes on Google's end. So it may or may not continue to work in the future. Such is life with Beta status. Any plugins that use it should consider upgrading to V2 like we have done. 

We probably should have tagged v1.0 of this plugin so old accounts can still remain functional while they wait for this to occur. However the upgrade instructions via Google are one-way, so it's not possible to downgrade unless you have your old P12 file.

**Comment by Flynsarmy** [comment]
> The Google API client is still in beta and implemented some major breaking changes with the 2.0 release. This makes any plugin that uses the 1.0 library version incompatible until they update to 2.0 as well.

I'm happy to update my plugin but I'd prefer to wait until 2.0 is stable before doing so.
