### ISSUE TITLE
Dashboard Widgets Issue

### ISSUE THREAD

**Issue by wbridgett** [rainlab/googleanalytics-plugin#50]
Argument 1 passed to Google_Client::setCache() must be an instance of Google\Auth\CacheInterface, instance of RainLab\GoogleAnalytics\Classes\CacheItemPool given, called in /plugins/rainlab/googleanalytics/classes/Analytics.php on line 48 and defined

**Comment by wetgi** [comment]
I have the same problem

**Comment by mrbohnke** [comment]
Hi! I'm having a similar (the same?) issue, probably due to the fact that I'm already using google's apiclient package on my laravel instalation with another different purpose:
![](https://d17oy1vhnax1f7.cloudfront.net/items/2u1R3e2x2l2l0w0S322W/Screen%20Shot%202017-01-20%20at%2013.21.09.png)
Is there any workaround to make this work? It would be a shame having to choose one or the other.
Thank you for your time!
